<script setup lang="ts">
defineProps<{
  title: string;
  cover?: string;
  link?: string; 
}>();
</script>

<template>
  <div class="info custom-block">
    <div class="cover-container">
      <img v-if="cover" class="cover-image" :src="cover" />
    </div>
    <div class="content">
      <div class="title">
        <span>{{ title }}</span>
      </div>
      <div class="description">
        <slot />
      </div>
      <div>
        <a v-if="link" :href="link" target="_blank">豆瓣</a>
      </div>
    </div>
  </div>
</template>

<style scoped>
.custom-block {
  display: flex;
  gap: 16px;
  padding: 16px;
}

.custom-block :deep(p) {
  margin: 8px 0 !important;
}

.cover-container {
  width: 20%;
}

.cover-container .cover-image {
  display: block;
  width: 100%;
  /* Generated by https://shadows.brumm.af/ */
  box-shadow:
    0px 0.2px 1.2px rgba(0, 0, 0, 0.1),
    0px 0.5px 3.1px rgba(0, 0, 0, 0.069),
    0px 1.1px 6.4px rgba(0, 0, 0, 0.056),
    0px 2.2px 13.1px rgba(0, 0, 0, 0.044),
    0px 6px 36px rgba(0, 0, 0, 0.031);
}

.content {
  display: flex;
  flex-direction: column;
}

.content .title {
  font-weight: 600;
}

.content .description {
  flex: 1;
}
</style>
